Vu360Sol.Web/Controllers/SalePersonController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Vu360Sol.ViewModel.Common;
using Vu360Sol.ViewModel.SalePersons;
using Vu360Sol.ViewModel.SharedViewModels;

namespace Vu360Sol.Web.Controllers
{
    [Authorize]
    public class SalePersonController : Controller
    {
        // GET: SalePerson
        public ActionResult SalePersonList()
        {
            return View();
        }
        public ActionResult SalePersonListPage(int PageNo = 1, string Search = "")
        {
            var data = new { PageNo, Search, PageSize = Utility.PageSize };
            var SerializeObject = JsonConvert.SerializeObject(data);
            SalePersonViewModelPaginationModel pageModel = new SalePersonViewModelPaginationModel();
            using (var client = Utility.GetHttpClient())
            {
                var myContent = JsonConvert.SerializeObject(SerializeObject);
                var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                var byteContent = new ByteArrayContent(buffer);
                byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/Json");
                var responseTask = client.PostAsync("saleperson/getall", byteContent);
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<SalePersonViewModelPaginationModel>();
                    readTask.Wait();
                    pageModel = readTask.Result;
                    pageModel.page = new Pager(pageModel.Count, PageNo, Utility.PageSize);
                    pageModel.SearchTerm = Search;
                    ModelState.Clear();
                    return PartialView("_SalePersonListPartial", pageModel);
                }
                else
                {
                    pageModel.salePersonViewModels = Enumerable.Empty<SalePersonViewModel>();
                    ModelState.AddModelError(string.Empty, "Server error try after some time.");
                }
            }
                return PartialView("_SalePersonListPartial", pageModel);
        }
        [HttpGet]
        public ActionResult CreateSalePerson()
        {
            List<GenderViewModel> genders = null;
            using (var client = Utility.GetHttpClient())
            {
                var model = Task.Run(async () => await client.GetAsync("saleperson/getallgender")).Result;
                if (model.IsSuccessStatusCode)
                {
                    genders = Task.Run(async () => await model.Content.ReadAsAsync<List<GenderViewModel>>()).Result;
                }
                ViewBag.Gender = genders;
            }
                return View();
        }
        [HttpPost]
        public ActionResult CreateSalePerson(SalePersonViewModel model,HttpPostedFileBase file)
        {

            string FinalResult = null;
            if (file != null)
            {
                string filename = file.FileName.ToLower().ToString();
                string[] exts = filename.Split('.');
                string name = exts[0].ToString() + Utility.getDefaultTime().ToString("yyyyMMddHHmmss");//DateTime.Now.ToString("yyyyMMddHHmmss")
                string ext = exts[1].ToString();
                FinalResult = name + "." + ext;
                string path = Path.Combine(Server.MapPath("~/UploadedFiles/"), Path.GetFileName(FinalResult));
                file.SaveAs(path);
            }
            int UserID = Convert.ToInt32(Session["UserId"]);

            model.ImagePath = FinalResult;
            model.User.RoleId = 3;
            model.User.CreatedOn = Utility.getDefaultTime();
            model.User.CreatedBy = UserID;
            model.CreatedOn = Utility.getDefaultTime();
            model.CreatedBy = UserID;
            model.ImagePath = FinalResult;
            model.User.IsActive = true;
            model.IsActive = true;
            using (var client = Utility.GetHttpClient()) 
            {
                var myContent = JsonConvert.SerializeObject(model);
                var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                var byteContent = new ByteArrayContent(buffer);
                byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                HttpResponseMessage response = Task.Run(async () => await client.PostAsync("saleperson/create/", byteContent)).Result;
            }
            return RedirectToAction("SalePersonList");
        }
        [HttpGet]
        public ActionResult EditSalePerson(int id)
        {
            List<GenderViewModel> genders = null;
            SalePersonViewModel model;
            using (var client = Utility.GetHttpClient())
            {
                var responseTask = client.GetAsync("saleperson/getbyid/" + id + "");
                responseTask.Wait();
                var result = responseTask.Result;
                var readTask = result.Content.ReadAsAsync<SalePersonViewModel>();
                readTask.Wait();
                model = readTask.Result;


                var gendermodel = Task.Run(async () => await client.GetAsync("saleperson/getallgender")).Result;
                if (gendermodel.IsSuccessStatusCode)
                {
                    genders = Task.Run(async () => await gendermodel.Content.ReadAsAsync<List<GenderViewModel>>()).Result;
                }
                ViewBag.Gender = genders;
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult EditSalePerson(SalePersonViewModel model, HttpPostedFileBase file)
        {
            if (file==null)
            {
                model.ImagePath = model.ImagePath;
            }
            else
            {
                string filename = file.FileName.ToLower().ToString();
                string[] exts = filename.Split('.');
                string name = exts[0].ToString() + Utility.getDefaultTime().ToString("yyyyMMddHHmmss");// DateTime.Now.ToString("yyyyMMddHHmmss")
                string ext = exts[1].ToString();
                string FinalResult = name + "." + ext;
                string _ImagesPath = "~/UploadedFiles/";

                // Save New File....
                string path = Path.Combine(Server.MapPath(_ImagesPath), Path.GetFileName(FinalResult));
                file.SaveAs(path);

                model.ImagePath = FinalResult;
            }
            using (var client = Utility.GetHttpClient())
            {
                int UserID = Convert.ToInt32(Session["UserId"]);
                var salePerson = new SalePersonViewModel();
                var responseT = client.GetAsync("salePerson/getbyid/" + model.Id + "");
                responseT.Wait();
                var dr = responseT.Result.Content.ReadAsAsync<SalePersonViewModel>();
                salePerson = dr.Result;
                if (salePerson != null)
                {
                    model.CreatedOn = salePerson.CreatedOn == null ? DateTime.Now : salePerson.CreatedOn;
                    model.User.CreatedOn = salePerson.User.CreatedOn == null ? DateTime.Now : salePerson.User.CreatedOn;
                    model.CreatedBy = salePerson.CreatedBy == null ? 1 : salePerson.User.CreatedBy;
                    model.User.CreatedBy = salePerson.User.CreatedBy == null ? 1 : salePerson.User.CreatedBy;
                }
                model.User.ModifiedOn = Utility.getDefaultTime();
                model.User.ModifiedBy = UserID == 0 ? 0 : UserID;
                model.ModifiedOn = Utility.getDefaultTime();
                model.ModifiedBy = UserID == 0 ? 0 : UserID;
                var myContent = JsonConvert.SerializeObject(model);
                var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                var byteContent = new ByteArrayContent(buffer);
                byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                HttpResponseMessage response = Task.Run(async () => await client.PostAsync("saleperson/update/", byteContent)).Result;
            }
            return RedirectToAction("SalePersonList");
        }
        public JsonResult Delete(int id)
        {
            using (var client = Utility.GetHttpClient())
            {
                var responseTask = client.GetAsync("saleperson/delete/" + id + "");
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    return Json("True");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error try after some time.");
                }
            }
            return Json("True");
        }
        public JsonResult SalePersonDropDown()
        {
            IEnumerable<SalePersonViewModel> salePeople = null;
            using (var client = Utility.GetHttpClient())
            {
                var responseTask = client.GetAsync("saleperson/getall");

                responseTask.Wait();
                //To store result of web api response.   
                var result = responseTask.Result;
                //If success received   
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<SalePersonViewModel>>();
                    readTask.Wait();
                    salePeople = readTask.Result;
                }
                else
                {
                    //Error response received   
                    salePeople = Enumerable.Empty<SalePersonViewModel>();
                    ModelState.AddModelError(string.Empty, "Server error try after some time.");

Vu360Sol.Web/Views/SalePerson/SalePersonList.cshtml
@model IEnumerable<Vu360Sol.ViewModel.SalePersons.SalePersonViewModel>
@{
    ViewBag.Title = "SalePersonList";
    Layout = "~/Views/Shared/_Theme2Layout.cshtml";
}
<section id="content">
    <div class="content-wrap">
        <div class="container clearfix" style="max-width: 1450px !important">
            <div class="">
                <h1 class="text-center">Sale Persons</h1>
            </div>
            <div class="row gutter-40 col-mb-80">
                <div class="postcontent col-lg-10 offset-1">

                    <div id="partial" style="max-width:100% !important"></div>
                </div>
                <div class="col-lg-2"></div>
            </div>
        </div>
    </div>
</section>
@section scripts{
    <script>
    $(document).ready(function(){


        $.ajax({
            url: '@Url.Action("SalePersonListPage", "SalePerson")',
		})
            .done(function (response) {
                //debugger;
            $("#partial").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
    });
    </script>
    <script>
        function deleteSalePerson(Id) {
            var url = "/SalePerson/Delete/" + Id;


            swal({
                title: "Are you sure?",
                text: "Are you sure you want to delete this Task ?",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((ans) => {
                    if (ans) {
                        $.ajax({
                            url: url,
                            type: "POST",
                            success: function () {
                                //ele.closest("tr").remove();
                                window.location.href = "/SalePerson/SalePersonList/";
                            },
                            error: function () {

                                swal("Please Try Again...", {
                                    icon: "error",
                                });
                            }
                        });
                    }
                });

        }
    </script>

}
<input type="hidden" id="hiddenSalePerson" />
@*<script>
        var ConfirmDelete = function (id) {
            $("#hiddenSalePerson").val(id);
            $("#myModal").modal('show');

        }
        var DeleteEmployee = function () {
            $("#loaderDiv").show();
            var empId = $("#hiddenSalePerson").val();
            $.ajax({

                type: "POST",
                url: "/SalePerson/Delete",
                data: { id: empId },
                success: function (result) {
                    $("#loaderDiv").hide();
                    $("#myModal").modal("hide");
                    $(".row_" + empId).remove();
                    location.reload(true);
                }
            })
        }
    </script>*@
<div class="modal fade" id="myModal" style="margin-top: 80px; border-radius:0 !important">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <h4 style="color:black !important"><span class="la la-question-circle"></span> Are you sure you want to delete this SalePerson ? </h4>

                <div style="text-align:center;display:none" id="loaderDiv">
                    <img src="~/Content/canvas/WebSite Images/Loader.gif" width="250" />
                </div>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-block btn-default" data-dismiss="modal" style="color:white !important; border-radius:0 !important; background-color:#555">Cancel</a>
                <a href="#" class="btn btn-block btn-success" onclick="DeleteEmployee()" style="border-radius:0 !important; background-color:#1abc9c;color:white;margin-bottom:8px;">Confirm</a>
            </div>
        </div>
    </div>
</div>

Vu360Sol.Web/Views/SalePerson/_SalePersonListPartial.cshtml
@model Vu360Sol.ViewModel.SharedViewModels.SalePersonViewModelPaginationModel
<div class="row">
    <div class="col-lg-6">
        <a href="/SalePerson/CreateSalePerson" style="float:left; padding:8px !important;" class="button button-border button-white button-light button-large button-rounded text-right "><span>Create</span></a>
    </div>
    <div class="col-lg-4 offset-2">
        <div class="input-group mx-auto">
            <input class="form-control" id="searchInput" type="text" value="@Model.SearchTerm" placeholder="Search by First Name ,Last Name and Email">
            <div class="input-group-append">
                <button class="btn btn-info" type="button" id="searchbutton">
                    <i class="icon-search"></i>
                </button>
            </div>
        </div>
        @*<div class="input-group mx-auto" style="float:right;margin-top:11px;">
            <input class="form-control" id="searchInput" type="text" value="@Model.SearchTerm" placeholder="Search by First Name ,Last Name and Email" style="margin-bottom: 10px;">
        </div>*@
    </div>
</div>
<div class="table-responsive">
    <table class="table" id="content">
        <thead>
            <tr>
                <th>Image</th>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody id="myTable">
            @if (Model.salePersonViewModels.Count() == 0)
            {
                <tr>
                    <td colspan="4" style="text-align:center;font-size:20px;font-weight:bold;">
                        No SalePerson...
                        <a href="/SalePerson/CreateSalePerson" style="text-decoration:none">
                            <small>Create</small>
                        </a>
                    </td>
                </tr>
            }
            else
            {
                foreach (var item in Model.salePersonViewModels)
                {
                    <tr id="contentrow">
                        <td>
                            @if (item.ImagePath == null)
                            {
                                <a href="@Url.Action("EditSalePerson","SalePerson",new { id = item.Id})">
                                    <img src="~/Content/canvas/WebSite Images/fuser.png" style="width:50px;height:50px;border-radius:25px;" />
                                </a>
                            }
                            else
                            {
                                <a href="@Url.Action("EditSalePerson","SalePerson",new { id = item.Id})">
                                    <img src="~/UploadedFiles/@item.ImagePath" style="width:50px;height:50px;border-radius:25px;" />
                                </a>
                            }
                        </td>
                        <td>@item.User.FullName</td>
                        <td>@item.User.Email</td>
                        <td>@item.User.PhoneNumber</td>
                        <td>
                            <ul class="navbar-nav mx-auto absolute-right ">
                                <li class="nav-item dropdown">
                                    <a class="" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="icon icon-list"></i>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdown05" style="min-width: 14rem !important;left:-41px !important">

                                        <a href="@Url.Action("EditSalePerson","SalePerson",new { id = item.Id})" style="text-decoration: none; padding: 6px;color:green">
                                            <i class="icon icon-edit"></i>
                                            Edit
                                        </a>
                                        <br />
                                        <a href="#" onclick="deleteSalePerson(@item.Id)" style="text-decoration: none; padding: 6px;color:red">
                                            <i class="icon icon-trash"></i>
                                            Delete
                                        </a>
                                    </div>
                                </li>
                            </ul>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <ul class="pagination pagination-rounded mt-5">
        @if (@Model.page != null && @Model.page.TotalPages > 1)
        {

            if (@Model.page.CurrentPage > 1)
            {
                <li class="page-item" title="First">
                    <a class="pageButtons page-link" data-pageno="1"><i class="icon-line-chevrons-left"></i></a>
                </li>

                <li class="page-item" title="Previous">
                    <a class="pageButtons page-link" data-pageno="@(@Model.page.CurrentPage - 1)"><i class="icon-line-chevron-left"></i></a>
                </li>
            }
            for (var page = @Model.page.StartPage; page <= @Model.page.EndPage; page++)
            {
                string activeClass = @Model.page.CurrentPage == page ? "active" : string.Empty;

                <li class="page-item @activeClass">
                    <a class="pageButtons page-link" data-pageno="@page">@page</a>

                </li>
            }
            if (@Model.page.CurrentPage < @Model.page.TotalPages)
            {
                <li class="page-item" title="Next">
                    <a class="pageButtons page-link" data-pageno="@(@Model.page.CurrentPage + 1)"><i class="icon-line-chevron-right"></i></a>
                </li>
                <li class="page-item" title="Last">
                    <a class="pageButtons page-link" data-pageno="@Model.page.TotalPages"><i class="icon-line-chevrons-right"></i></a>
                </li>
            }
        }
    </ul>
</div>
<script>
    $(".pageButtons").click(function () {
        //debugger;
        var data= {
				pageNo: $(this).attr("data-pageNo"),
                search: '@Model.SearchTerm',
                UserId: $("#hfUserId").val()
        }
        SendRequest(data);
	});
    $.fn.pressEnter = function (fn) {
        return this.each(function () {
            $(this).bind('enterPress', fn);
            $(this).keyup(function (e) {
                if (e.keyCode == 13) {
                    $(this).trigger("enterPress");
                }
            })
        });
    };
    // On Enter
    $('#searchInput').pressEnter(function () {
        var data = {
            search: $('#searchInput').val()
        };
        SendRequest(data);
    });
    // For Loading Data.....
    $('#searchInput').on('input', function (e) {
        var data = {
            search: $('#searchInput').val()
        };
        if (data.search == "") {
            SendRequest(data);
        }
    });
    // On Click
    $('#searchbutton').on('click', function (e) {
        var data = {
            search: $('#searchInput').val()
        };
        SendRequest(data);
    });


    function SendRequest(data) {
        	$.ajax({
			url: '@Url.Action("SalePersonListPage", "SalePerson")',
			data:data
		})
            .done(function (response) {
                //debugger;
                $("#partial").html(response);
                var search = $("#searchInput");
                search.focus();
                var strLength = search.val().length * 2;
                search[0].setSelectionRange(strLength, strLength);

            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                //alert("FAIL");
            });
    };
</script>