Vu360Sol.Web/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vu360Sol.ViewModel;
using Vu360Sol.ViewModel.RequestDemoes;
using Vu360Sol.ViewModel.Account;
using System.Net.Http;
using Vu360Sol.ViewModel.Visitors;
using Vu360Sol.ViewModel.SharedViewModels;
using System.Net.Http.Headers;
using Newtonsoft.Json;

namespace Vu360Sol.Web.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Home()
        {
            return View();
        }


        /// <summary>
        public ActionResult RequestDemoListPage(int PageNo = 1, string Search = "", int Days = 1)
        {
            ViewBag.Register = false;
            var data = new { PageNo, Search, PageSize = Utility.PageSize, Days };
            var SerializeObject = JsonConvert.SerializeObject(data);
            RequestDemoViewModelPaginationModel pageModel = new RequestDemoViewModelPaginationModel();

            using (var client = Utility.GetHttpClient())
            {
                var myContent = JsonConvert.SerializeObject(SerializeObject);
                var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                var byteContent = new ByteArrayContent(buffer);
                byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/Json");
                var responseTask = client.PostAsync("Dashboard/GetRequestDemo", byteContent);
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<RequestDemoViewModelPaginationModel>();
                    readTask.Wait();
                    pageModel = readTask.Result;
                    pageModel.page = new Pager(pageModel.Count, PageNo, Utility.PageSize);
                    pageModel.SearchTerm = Search;
                    ModelState.Clear();
                    return PartialView("_RequestDemo", pageModel);
                }
                else
                {
                    //Error response received   
                    pageModel.requestDemoViewModels = Enumerable.Empty<RequestDemoViewModel>();
                    ModelState.AddModelError(string.Empty, "Server error try after some time.");
                }
            }
            return PartialView("_RequestDemo", pageModel);
        }
        public ActionResult Approval(int PageNo = 1,  string Search = "", int Days = 1)
        {
            ViewBag.Register = false;
            var data = new { PageNo, Search, PageSize = Utility.PageSize,
                Days
            };
            var SerializeObject = JsonConvert.SerializeObject(data);
            UserViewModelPaginationModel pageModel = new UserViewModelPaginationModel();

            using (var client = Utility.GetHttpClient())
            {
                var myContent = JsonConvert.SerializeObject(SerializeObject);
                var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                var byteContent = new ByteArrayContent(buffer);
                byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/Json");
                var responseTask = client.PostAsync("Dashboard/getallinactiveUsers", byteContent);
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<UserViewModelPaginationModel>();
                    readTask.Wait();
                    pageModel = readTask.Result;
                    pageModel.page = new Pager(pageModel.Count, PageNo, Utility.PageSize);
                    pageModel.SearchTerm = Search;
                    ModelState.Clear();
                    return PartialView("_ApprovalPartial", pageModel);
                }
                else
                {
                    //Error response received   
                    pageModel.userViewModels = Enumerable.Empty<UserViewModel>();
                    ModelState.AddModelError(string.Empty, "Server error try after some time.");
                }
            }
            return PartialView("_ApprovalPartial", pageModel);
        }
        public ActionResult UserApproval(int Id)
        {
            using (var client = Utility.GetHttpClient())
            {
                var responseTask = client.GetAsync("Dashboard/Approve/" + Id + "");
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Home");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error try after some time.");
                }
            }
            return RedirectToAction("Home");
        }
        public ActionResult GetAllVisitorForLearning(int PageNo = 1, string Search = "", int Days = 1)
        {
            var data = new { PageNo, Search, PageSize = Utility.PageSize, Days };
            var SerializeObject = JsonConvert.SerializeObject(data);
            VisitorViewModelPaginationModel pageModel = new VisitorViewModelPaginationModel();

            using (var client = Utility.GetHttpClient())
            {
                var myContent = JsonConvert.SerializeObject(SerializeObject);
                var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                var byteContent = new ByteArrayContent(buffer);
                byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/Json");
                var responseTask = client.PostAsync("Dashboard/GetAllVisitorForLearning/", byteContent);
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<VisitorViewModelPaginationModel>();
                    readTask.Wait();
                    pageModel = readTask.Result;
                    pageModel.page = new Pager(pageModel.Count, PageNo, Utility.PageSize);
                    pageModel.SearchTerm = Search;
                    ModelState.Clear();
                    return PartialView("_VisitorsLearningPartial", pageModel);

                }
                else
                {
                    pageModel.visitorViewModels = Enumerable.Empty<VisitorViewModel>();
                    ModelState.AddModelError(string.Empty, "Server error try after some time.");
                }
            }
            return PartialView("_VisitorsLearningPartial", pageModel);
        }

        public PartialViewResult GetAllVisitorForStarting(int PageNo = 1, string Search = "", int Days = 1)
        {
            var data = new { PageNo, Search, PageSize = Utility.PageSize, Days };
            var SerializeObject = JsonConvert.SerializeObject(data);
            VisitorViewModelPaginationModel pageModel = new VisitorViewModelPaginationModel();

            using (var client = Utility.GetHttpClient())
            {
                var myContent = JsonConvert.SerializeObject(SerializeObject);
                var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                var byteContent = new ByteArrayContent(buffer);
                byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/Json");
                var responseTask = client.PostAsync("Dashboard/GetAllVisitorForStarting/", byteContent);
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<VisitorViewModelPaginationModel>();
                    readTask.Wait();
                    pageModel = readTask.Result;
                    pageModel.page = new Pager(pageModel.Count, PageNo, Utility.PageSize);
                    pageModel.SearchTerm = Search;
                    ModelState.Clear();
                    return PartialView("_VisitorsStartingPartial", pageModel);

                }
                else
                {
                    pageModel.visitorViewModels = Enumerable.Empty<VisitorViewModel>();
                    ModelState.AddModelError(string.Empty, "Server error try after some time.");
                }
            }
            return PartialView("_VisitorsStartingPartial", pageModel);
        }
    }
}

Vu360Sol.Web/Controllers/FailToImportDoctorsLogController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using Vu360Sol.ViewModel.Logs;
using Vu360Sol.ViewModel.SharedViewModels;

namespace Vu360Sol.Web.Controllers
{
    public class FailToImportDoctorsLogController : Controller
    {
        // GET: FailToImportDoctorsLog
        public ActionResult FailToImportDoctorsLog()
        {
            return View();
        }
        public ActionResult FailToImportDoctorsPage(int PageNo = 1, string Search = "")
        {
            var data = new { PageNo, Search, PageSize = Utility.PageSize };
            var SerializeObject = JsonConvert.SerializeObject(data);
            FailToImportDoctorsLogPaginationModel pageModel = new FailToImportDoctorsLogPaginationModel();
            using (var client = Utility.GetHttpClient())
            {
                var myContent = JsonConvert.SerializeObject(SerializeObject);
                var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                var byteContent = new ByteArrayContent(buffer);
                byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/Json");
                var responseTask = client.PostAsync("FailToImportDoctorsLog/GetAllPage/", byteContent);
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<FailToImportDoctorsLogPaginationModel>();
                    readTask.Wait();
                    pageModel = readTask.Result;
                    pageModel.page = new Pager(pageModel.Count, PageNo, Utility.PageSize);
                    pageModel.SearchTerm = Search;
                    ModelState.Clear();
                    return PartialView("_FailToImportDoctorsLogPartial", pageModel);

                }
                else
                {
                    pageModel.FailToImportDoctorsLogViewModels = Enumerable.Empty<FailToImportDoctorsLogViewModel>();
                    ModelState.AddModelError(string.Empty, "Server error try after some time.");
                }
            }
            return PartialView("_FailToImportDoctorsLogPartial", pageModel);
        }
    }
}

Vu360Sol.Web/Controllers/HomeController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Vu360Sol.ViewModel;
using Vu360Sol.ViewModel.Visitors;

namespace Vu360Sol.Web.Controllers
{
    public class HomeController : Controller
    {
        
        // GET: Home
        [Route("")]
        public ActionResult Index()
        {
            return View();
        }

        [Route("Practices")]
        public ActionResult Practices()
        {
            return View();
        }

        [Route("Patients")]
        public ActionResult Patients()
        {
            return View();
        }

        [Route("Partners")]
        public ActionResult Partners()
        {
            return View();
        }

        [Route("Insurers")]
        public ActionResult Insurers()
        {
            return View();
        }

        [Route("FAQ")]
        public ActionResult FAQ()
        {
            return View();
        }

        [Route("AboutUs")]
        public ActionResult AboutUs()
        {
            return View();
        }

        [Route("WhyPartner")]
        public ActionResult WhyPartner()
        {
            return View();
        }

        [Route("ContactUs")]
        public ActionResult ContactUs()
        {
            return View();
        }

        [Route("Howworks")]
        public ActionResult Howworks()
        {
            return View();
        }

        [Route("Introduction")]
        public ActionResult Introduction()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> SendVisitorEmailIntro(VisitorViewModel visitor)
        {
            try
            {
                if (visitor != null)
                {
                    visitor.CreatedOn = Utility.getDefaultTime();

                    using (var client = Utility.GetHttpClient())
                    {
                        var myContent = JsonConvert.SerializeObject(visitor);
                        var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                        var byteContent = new ByteArrayContent(buffer);
                        byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                        HttpResponseMessage response = Task.Run(async () => await client.PostAsync("visitor/create/", byteContent)).Result;
                        if (response.IsSuccessStatusCode)
                        {
                            var email = await new Email().contactUsEmail(visitor);
                            if (email)
                            {
                                var visitoremail = await new Email().contactVisitorEmail(visitor);
                                if (visitoremail)
                                {
                                    return Json(new { success = true, responseText = "Thank you for your registration. A representative from the StreamVitals team will contact you to discuss next steps." }, JsonRequestBehavior.AllowGet);
                                }
                                else
                                {
                                    return Json(new { success = false, responseText = "Face issue while processing request. Please try later." }, JsonRequestBehavior.AllowGet);
                                }
                            }
                            else
                            {
                                return Json(new { success = false, responseText = "Face issue while processing request. Please try later." }, JsonRequestBehavior.AllowGet);
                            }
                        }
                        else
                        {
                            return Json(new { success = false, responseText = "Face issue while processing request.Please try later." }, JsonRequestBehavior.AllowGet);
                        }
                    }
                }
                return View();
            }
            catch (Exception)
            {
                throw;
            }


        }


        [Route("Introenvelope")]
        public ActionResult Introenvelope()
        {
            return View();
        }

        [Route("Introductionenvelope")]
        public ActionResult Introductionenvelope()
        {
            return View();
        }

        [Route("Introletter")]
        public ActionResult Introletter()
        {
            return View();
        }


        [HttpPost]
        public async Task<ActionResult> SendVisitorEmail(VisitorViewModel visitor)
        {
            try
            {
                if (visitor != null)
                {
                    using (var client = Utility.GetHttpClient())
                    {
                        // visitor.CreatedOn = DateTime.Now;
                        visitor.CreatedOn = Utility.getDefaultTime();
                        var myContent = JsonConvert.SerializeObject(visitor);
                        var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                        var byteContent = new ByteArrayContent(buffer);
                        byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                        var senddata = await client.PostAsync("user/addVisitor", byteContent);
                        var jsonstring = await senddata.Content.ReadAsStringAsync();
                        if (senddata.IsSuccessStatusCode)
                        {
                            var email = await new Email().contactUsEmail(visitor);
                            if (email)
                            {
                                return Json(new { success = true, responseText = "Email Sent Successfully. Thank you for contacting us." }, JsonRequestBehavior.AllowGet);
                            }
                            else
                            {
                                return Json(new { success = false, responseText = "Face issue while sending email. Please try later." }, JsonRequestBehavior.AllowGet);
                            }
                        }
                        //else
                        //{
                        //    return Json(new { success = false, responseText = "Face issue while sending email. Please try later." }, JsonRequestBehavior.AllowGet);
                        //}
                    }
                }
                return View();
            }
            catch (Exception)
            {
                throw;
            }
            
           
        }
    }
}

Vu360Sol.Web/Views/Dashboard/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_Theme2Layout.cshtml";
}
<section id="content">
    <div class="content-wrap">
        <div class="container clearfix">
            <div class="row">
                <div class="col-lg-12">
                    <div class="tabs mx-auto mb-0 clearfix" id="tab-login-register">
                        <ul class="tab-nav tab-nav2 center clearfix">
                            <li class="inline-block active"><a id="RequestsForDemo" style="cursor:pointer;">Requests For Demo</a></li>
                            <li class="inline-block"><a id="inquiries" style="cursor:pointer;">inquiries</a></li>
                            <li class="inline-block"><a id="Approval" style="cursor:pointer;">Approval</a></li>
                        </ul>
                        <div class="tab-container">
                            <div class="tab-content">
                                <div class="card mb-0">
                                    <div class="card-body">
                                        <div id="partial">

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section scripts{
    <script>
    $(document).ready(function(){

        $("#RequestsForDemo").css("background-color", "#1c79bc");
        $("#RequestsForDemo").css("color", "white");

        $.ajax({
            url: '@Url.Action("FailToImportDoctorsPage", "FailToImportDoctorsLog")',
		})
        .done(function (response) {
            $("#partial").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
    });
        $("#RequestsForDemo").click(function () {
            $("#partial").load('/Inquiry/GetAllVisitorForLearning');
            
            $("#LearnMore").css("background-color", "#1c79bc");
            $("#LearnMore").css("color", "white");
            $("#ReadytoGetStarted").css("background-color", "#f5f5f5");
            $("#ReadytoGetStarted").css("color", "inherit");
        });
    </script>
}

Vu360Sol.Web/Views/Dashboard/Home.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Theme2Layout.cshtml";
}


<section id="content">
    <div class="content-wrap" style="padding:45px !important;">
        <div class="container clearfix">
            <div class="row gutter-40 ">
                <div class="postcontent col-lg-6">
                    <div id="requestDemoPartial" style="max-width:100% !important"></div>
                </div>

                <div class="postcontent col-lg-6">
                    <div id="approvalPartial" style="max-width:100% !important"></div>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="content">
    <div class="content-wrap" style="padding:0px !important;">
        <div class="container clearfix">

            <div class="row gutter-40 col-mb-80">

                <div class="postcontent col-lg-12 ">

                    <div class="jumbotron" style="background-color: #f9f9f9c7 !important">
                        <h4>Inquiries</h4>
                        @*<div class="row">
                            <div class="col-lg-6">

                            </div>
                            <div class="col-lg-6">
                                <div class="form-group ">
                                    <select id="Gender" name="" class="form-control">
                                        <option value="3" selected disabled>None</option>
                                        <option value="1">Last 7 days</option>
                                        <option value="2">Last 30 days</option>
                                    </select>
                                </div>
                            </div>
                        </div>*@

                        <div class="tabs mx-auto mb-0 clearfix" id="tab-login-register">
                            <ul class="tab-nav tab-nav2 center clearfix">
                                <li class="inline-block active"><a id="LearnMore" style="cursor:pointer;">Learn More</a></li>
                                <li class="inline-block"><a id="ReadytoGetStarted" style="cursor:pointer;">Ready to Get Started</a></li>
                            </ul>
                            <div class="tab-container">
                                <div class="tab-content">
                                    <div class="card mb-0">
                                        <div class="card-body">
                                            <div id="partialview">

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row" style=" margin-top: 20px;">
                            <div class="col-md-6 text-right"><a href="/Inquiry/Index" class="btn btn-primary" style="background-color:#1abc9c;">View All</a></div>
                        </div>
                    </div>

                </div>

            </div>

        </div>
    </div>
</section>
@Html.Partial("_NoteModelDashboardRequestDemo")
@Html.Partial("_DetailModelDashboardRequestDemo")
@section scripts {
    <script>
    $(document).ready(function(){


        $.ajax({
            url: '@Url.Action("Approval", "Dashboard")',
		})
            .done(function (response) {
                
            $("#approvalPartial").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });

        $.ajax({
            url: '@Url.Action("RequestDemoListPage", "Dashboard")',
		})
            .done(function (response) {
                
                $("#requestDemoPartial").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });

    });
    </script>
    <script>
        $("#LearnMore").click(function () {
            $.ajax({
            url: '@Url.Action("GetAllVisitorForLearning", "Dashboard")',
		    })
            .done(function (response) {
                $("#LearnMore").css("background-color", "#1c79bc");
                $("#LearnMore").css("color", "white");
                $("#ReadytoGetStarted").css("background-color", "#f5f5f5");
                $("#ReadytoGetStarted").css("color", "inherit");
                $("#partialview").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
            });
        });
    </script>
    <script>
        $("#ReadytoGetStarted").click(function () {
           $.ajax({
            url: '@Url.Action("GetAllVisitorForStarting", "Dashboard")',
		    })
            .done(function (response) {
                $("#ReadytoGetStarted").css("background-color", "#1c79bc");
                $("#ReadytoGetStarted").css("color", "white");
                $("#LearnMore").css("background-color", "#f5f5f5");
                $("#LearnMore").css("color", "inherit");
                $("#partialview").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
            });
        });
    </script>
    <script>
    $(document).ready(function(){


        $.ajax({
            url: '@Url.Action("GetAllVisitorForLearning", "Dashboard")',
		})
            .done(function (response) {
                $("#LearnMore").css("background-color", "#1c79bc");
                $("#LearnMore").css("color", "white");
                $("#partialview").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
    });
    </script>
    <script>
        function NoteModalDB(Id) {
            $("#ReferenceId").val(Id);
            NotesDB(Id);
            $("#notemodalDB").modal("show");
        }
        function NotesDB(Id) {
            $.ajax({
                type: "GET",
                url: "/Note/List/" + Id,
                contentType: "application/json;charset=utf-8",
                dataType: "json",
                success: function (data) {
                    debugger
                    $('#NotesTableDB').html('');
                    $.each(data, function (i, item) {
                        rows = "<tr><td>" + item.Discription + "</td><td><a data-model-id='" + item.Id + "' onclick='Delete(this)' style='cursor:pointer;color:red'><i class='icon icon-trash'></i></a></td></tr>";
                        $('#NotesTableDB').append(rows);
                    });
                },
                error: function (result) {
                    alert('Please Try Again...');
                }
            });
        }


        $(document).ready(function () {

            // Button Working
            $('#btnnote').prop('disabled', true);
            $('#Discription').keyup(function () {
                if ($(this).val() != '') {
                    $('#btnnote').prop('disabled', false);
                }
            });

            // Save Note

            $("#btnnote").click(function (e) {

                if ($("#Discription").val() == "") {
                    $("#Discription").focus();
                    $("#errmsg").html("Please Fill Notes Field").show().fadeOut(5000);
                    return false;
                }

                e.preventDefault();
                $.ajax({
                    type: "POST",
                    //beforeSend: function () {
                    //    $("#btnnote").html("Please Wait...");
                    //},
                    url: "/Note/Insert",
                    data: $("#formnote").serialize(),
                    success: function (result) {
                        $('#Discription').val('');
                        if (result) {
                            var Id = $("#ReferenceId").val();
                            NotesDB(Id)
                        }
                    },
                    //complete: function () {
                    //    $("#btnnote").html("Add Notes");
                    //    },
                    error: function (result) {
                        alert('Please Try Again...');
                    }
                });
            });
        });
    </script>
    <script>
        function RequestDemoDetail(Id) {
            debugger
            //$("#ReferenceId").val(Id);
            RequestDemoDetails(Id);
            
        }
        function RequestDemoDetails(Id) {
            debugger
            $.ajax({
                type: "GET",
                url: "/RequestDemo/GetById/" + Id,
                contentType: "application/json;charset=utf-8",
                dataType: "json",
                success: function (data) {
                    debugger
                    $("#fname").html(data.FirstName);
                    $("#lname").html(data.LastName);
                    $("#fullname").html(data.FullName);
                    $("#email").html(data.Email);
                    $("#phone").html(data.Phone);
                    $("#location").html(data.Location);
                    $("#date").html(data.Dates);
                    $("#time").html(data.Time);
                    //$("#dname").html(data.Doctor.FirstName);
                    $("#requestDemoModel").modal("show");
                },
                error: function (result) {
                    alert('Please Try Again...');
                }
            });
        }
    </script>

}