Vu360Sol.Web/Controllers/SalePersonDashboardController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using Vu360Sol.ViewModel.Doctors;
using Vu360Sol.ViewModel.SalePersons;
using Vu360Sol.ViewModel.SharedViewModels;
using Vu360Sol.ViewModel.Visitors;

namespace Vu360Sol.Web.Controllers
{
    public class SalePersonDashboardController : Controller
    {
        // GET: SalePersonDashboard
        public ActionResult Index()
        {
            return View();
        }
         public ActionResult ContactedDoctorsPage(int PageNo = 1, string Search = "",int Days = 1)
          {
            // var t = Session["UserId"];
           var SalePersonId = Convert.ToInt32(Session["UserId"]);
            var data = new { PageNo, Search, Days, SalePersonId, PageSize = Utility.PageSize };
            var SerializeObject = JsonConvert.SerializeObject(data);
            DoctorPaginationModel pageModel = new DoctorPaginationModel();
           
            using (var client = Utility.GetHttpClient())
            {
                var myContent = JsonConvert.SerializeObject(SerializeObject);
                var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                var byteContent = new ByteArrayContent(buffer);
                byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/Json");
                var responseTask = client.PostAsync("SalePersonDashboard/ContactedDoctors/", byteContent);
                responseTask.Wait();
                //To store result of web api response.   
                var result = responseTask.Result;
                //If success received   
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<DoctorPaginationModel>();
                    readTask.Wait();
                     pageModel = readTask.Result;
                    pageModel.page = new Pager(pageModel.Count, PageNo, Utility.PageSize);
                    pageModel.SearchTerm = Search;
                    ModelState.Clear();
                    return PartialView("_ContactedDoctorsDB", pageModel);
                    
                }
                else
                {
                    //Error response received   
                    pageModel.doctors = Enumerable.Empty<DoctorViewModel>();
                    ModelState.AddModelError(string.Empty, "Server error try after some time.");
                }
            }
            return PartialView("_ContactedDoctorsDB", pageModel);
            //return View(model);
        }

        public ActionResult DoctorAssignedList(int PageNo = 1, string Search = "", int Days = 1)
        {

           var SalePersonId = Convert.ToInt32(Session["UserId"]);

            var data = new { PageNo, Search, Days, SalePersonId, PageSize = Utility.PageSize };
            var SerializeObject = JsonConvert.SerializeObject(data);

            DoctorAssignedPaginationModel pageModel = new DoctorAssignedPaginationModel();
            using (var client = Utility.GetHttpClient())
            {
                var myContent = JsonConvert.SerializeObject(SerializeObject);
                var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                var byteContent = new ByteArrayContent(buffer);
                byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/Json");
                var responseTask = client.PostAsync("SalePersonDashboard/DoctorAssignedList/", byteContent);

                responseTask.Wait();
                var result = responseTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<DoctorAssignedPaginationModel>();
                    readTask.Wait();
                    pageModel = readTask.Result;
                    pageModel.page = new Pager(pageModel.Count, PageNo, Utility.PageSize);
                    pageModel.SearchTerm = Search;
                    ModelState.Clear();
                    return PartialView("_DoctorAssignedListDB", pageModel);
                }
                else
                {
                    pageModel.doctorsAssigned = Enumerable.Empty<DoctorAssignedViewModel>();

                    ModelState.AddModelError(string.Empty, "Server error try after some time.");
                }
            }
            return PartialView("_DoctorAssignedListDB", pageModel);
        }

        public ActionResult GetAllVisitorForLearning(int PageNo = 1, string Search = "", int Days = 1)
        {
            var data = new { PageNo, Search, PageSize = Utility.PageSize, Days };
            var SerializeObject = JsonConvert.SerializeObject(data);
            VisitorViewModelPaginationModel pageModel = new VisitorViewModelPaginationModel();

            using (var client = Utility.GetHttpClient())
            {
                var myContent = JsonConvert.SerializeObject(SerializeObject);
                var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                var byteContent = new ByteArrayContent(buffer);
                byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/Json");
                var responseTask = client.PostAsync("Dashboard/GetAllVisitorForLearning/", byteContent);
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<VisitorViewModelPaginationModel>();
                    readTask.Wait();
                    pageModel = readTask.Result;
                    pageModel.page = new Pager(pageModel.Count, PageNo, Utility.PageSize);
                    pageModel.SearchTerm = Search;
                    ModelState.Clear();
                    return PartialView("_VisitorsLearningPartial", pageModel);

                }
                else
                {
                    pageModel.visitorViewModels = Enumerable.Empty<VisitorViewModel>();
                    ModelState.AddModelError(string.Empty, "Server error try after some time.");
                }
            }
            return PartialView("_VisitorsLearningPartial", pageModel);
        }

        public PartialViewResult GetAllVisitorForStarting(int PageNo = 1, string Search = "", int Days = 1)
        {
            var data = new { PageNo, Search, PageSize = Utility.PageSize, Days };
            var SerializeObject = JsonConvert.SerializeObject(data);
            VisitorViewModelPaginationModel pageModel = new VisitorViewModelPaginationModel();

            using (var client = Utility.GetHttpClient())
            {
                var myContent = JsonConvert.SerializeObject(SerializeObject);
                var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                var byteContent = new ByteArrayContent(buffer);
                byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/Json");
                var responseTask = client.PostAsync("Dashboard/GetAllVisitorForStarting/", byteContent);
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<VisitorViewModelPaginationModel>();
                    readTask.Wait();
                    pageModel = readTask.Result;
                    pageModel.page = new Pager(pageModel.Count, PageNo, Utility.PageSize);
                    pageModel.SearchTerm = Search;
                    ModelState.Clear();
                    return PartialView("_VisitorsStartingPartial", pageModel);

                }
                else
                {
                    pageModel.visitorViewModels = Enumerable.Empty<VisitorViewModel>();
                    ModelState.AddModelError(string.Empty, "Server error try after some time.");
                }
            }
            return PartialView("_VisitorsStartingPartial", pageModel);
        }
        public ActionResult GetById(int id)
        {
            DoctorAssignedViewModel requestDemo = null;
            using (var client = Utility.GetHttpClient())
            {
                var responseTask = client.GetAsync("SalePersonDashboard/GetById/" + id + "");
                responseTask.Wait();
                //To store result of web api response.   
                var result = responseTask.Result;
                //If success received   
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<DoctorAssignedViewModel>();
                    readTask.Wait();
                    requestDemo = readTask.Result;
                    return Json(requestDemo, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    //Error response received   
                    requestDemo = null;
                    ModelState.AddModelError(string.Empty, "Server error try after some time.");
                }
            }
            return Json(requestDemo, JsonRequestBehavior.AllowGet);
        }


    }
}

Vu360Sol.Web/Views/SalePersonDashboard/Index.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Theme2Layout.cshtml";
}


<section id="content">
    <div class="content-wrap" style="padding:45px !important;">
        <div class="container clearfix">
            <div class="row gutter-40 ">
                <div class="postcontent col-lg-6">
                    <div id="contactedPartial" style="max-width:100% !important"></div>
                </div>

                <div class="postcontent col-lg-6">
                    <div id="assignDoctorsPartial" style="max-width:100% !important"></div>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="content">
    <div class="content-wrap" style="padding:0px !important;">
        <div class="container clearfix">

            <div class="row gutter-40 col-mb-80">

                <div class="postcontent col-lg-12 ">

                    <div class="jumbotron" style="background-color: #f9f9f9c7 !important">
                        <h4>Inquiries</h4>
                        <div class="tabs mx-auto mb-0 clearfix" id="tab-login-register">
                            <ul class="tab-nav tab-nav2 center clearfix">
                                <li class="inline-block active"><a id="LearnMore" style="cursor:pointer;">Learn More</a></li>
                                <li class="inline-block"><a id="ReadytoGetStarted" style="cursor:pointer;">Ready to Get Started</a></li>
                            </ul>
                            <div class="tab-container">
                                <div class="tab-content">
                                    <div class="card mb-0">
                                        <div class="card-body">
                                            <div id="partialviewSPDB">

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row" style=" margin-top: 20px;">
                            <div class="col-md-6 text-right"><a href="/Inquiry/Index" class="btn btn-primary" style="background-color:#1abc9c;">View All</a></div>
                        </div>
                    </div>

                </div>

            </div>

        </div>
    </div>
</section>
@Html.Partial("_DrAssignDetailModel")
@section scriptsSalePersonDashboard {
    <script>
    $(document).ready(function(){


        $.ajax({
            url: '@Url.Action("ContactedDoctorsPage", "SalePersonDashboard")',
		})
            .done(function (response) {
                debugger;
                $("#contactedPartial").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });

        $.ajax({
            url: '@Url.Action("DoctorAssignedList", "SalePersonDashboard")',
		})
            .done(function (response) {
                debugger;
                $("#assignDoctorsPartial").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });

    });
    </script>
    <script>
        $("#LearnMore").click(function () {
            $.ajax({
            url: '@Url.Action("GetAllVisitorForLearning", "SalePersonDashboard")',
		    })
            .done(function (response) {
                $("#LearnMore").css("background-color", "#1c79bc");
                $("#LearnMore").css("color", "white");
                $("#ReadytoGetStarted").css("background-color", "#f5f5f5");
                $("#ReadytoGetStarted").css("color", "inherit");
                $("#partialviewSPDB").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
            });
        });
    </script>
    <script>
        $("#ReadytoGetStarted").click(function () {
           $.ajax({
            url: '@Url.Action("GetAllVisitorForStarting", "SalePersonDashboard")',
		    })
            .done(function (response) {
                $("#ReadytoGetStarted").css("background-color", "#1c79bc");
                $("#ReadytoGetStarted").css("color", "white");
                $("#LearnMore").css("background-color", "#f5f5f5");
                $("#LearnMore").css("color", "inherit");
                $("#partialviewSPDB").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
            });
        });
    </script>
    <script>
    $(document).ready(function(){


        $.ajax({
            url: '@Url.Action("GetAllVisitorForLearning", "SalePersonDashboard")',
		})
            .done(function (response) {
                $("#LearnMore").css("background-color", "#1c79bc");
                $("#LearnMore").css("color", "white");
                $("#partialviewSPDB").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
    });
    </script>

    <script>
        function DrAssignDetail(Id) {
            debugger
            //$("#ReferenceId").val(Id);
            DrAssignDetails(Id);

        }
        function DrAssignDetails(Id) {
            debugger
            $.ajax({
                type: "GET",
                url: "/SalePersonDashboard/GetById/" + Id,
                contentType: "application/json;charset=utf-8",
                dataType: "json",
                success: function (data) {
                    debugger
                    $("#fname").html(data.Doctor.User.FirstName);
                    $("#lname").html(data.Doctor.User.LastName);
                    $("#fullname").html(data.Doctor.User.FullName);
                    $("#email").html(data.Doctor.User.Email);
                    $("#phone").html(data.Doctor.User.PhoneNumber);
                    $("#npi").html(data.Doctor.NPI)
                    $("#providerType").html(data.Doctor.ProviderType);
                    if (data.Doctor.Practice != null) {
                        $("#practiceName").html(data.Doctor.Practice.Name);
                    }
                    $("#locationName").html(data.Doctor.LocationName);
                    $("#locationAddress").html(data.Doctor.LocationAddress);
                    $("#locationState").html(data.Doctor.LocationState);
                    $("#status").html(data.Doctor.Status.Name);
                    $("#DrAssignDetailModel").modal("show");
                },
                error: function (result) {
                    alert('Please Try Again...');
                }
            });
        }
    </script>

}

Vu360Sol.Web/Views/SalePersonDashboard/_ContactedDoctorsDB.cshtml
@model Vu360Sol.ViewModel.SharedViewModels.DoctorPaginationModel
<div class="jumbotron" style="background-color: #f9f9f9c7 !important;height: 735px;position: relative;">
    <h4>Contacted Doctors</h4>
    <div class="row">
        <div class="col-lg-6">
            <div class="form-group">
                <input class="form-control" id="searchInputContactedDoctors" type="text" value="@Model.SearchTerm" placeholder="Search by First Name ,Last Name and Email" style="margin-bottom: 10px;">
            </div>
        </div>
        <div class="col-lg-6">
            <select id="daysContactedDoctors" name="daysApproval" class="form-control">
                <option value="1" selected>Today</option>
                <option value="7">Last 7 days</option>
                <option value="30">Last 30 days</option>
            </select>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table" id="content">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Phone</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="myTable">

                @if (@Model.doctors == null || (@Model.doctors != null && @Model.doctors.Count() == 0))
                {
                    <tr>
                        <td colspan="5" style="text-align:center;font-size:20px;font-weight:bold;">
                            No Contacted Doctor...
                        </td>
                    </tr>
                }
                else
                {

                    foreach (var item in @Model.doctors)
                    {
                        <tr id="contentrow">
                            <td>
                                @if (item.ImagePath == null)
                                {
                                    <img src="~/Content/canvas/WebSite Images/fuser.png" style="width:50px;height:50px;border-radius:25px;" />
                                }
                                else
                                {
                                    <img src="~/UploadedFiles/@item.ImagePath" style="width:50px;height:50px;border-radius:25px;" />
                                }
                                <input type="hidden" id="hfId" value="@item.Id" />
                                <input type="hidden" id="hfIsUserRegisterd" value="@item.User.IsActive.ToString()" />
                            </td>
                            <td id="FirstName">
                                @item.User.FirstName

                            </td>
                            <td id="LastName">
                                @item.User.LastName

                            </td>
                            <td id="Phone">@item.User.PhoneNumber</td>
                            @*<td>
                                    <ul class="navbar-nav mx-auto absolute-right ">
                                        <li class="nav-item dropdown" style=" text-align: center;">

                                            <a class="" href="#" onclick="assign(@item.Id)" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <i class="icon icon-eye"></i>
                                            </a>
                                        </li>
                                    </ul>
                                </td>*@


                            <td>
                                <ul class="navbar-nav mx-auto absolute-right  ">
                                    <li class="nav-item dropdown">

                                        <a class="" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="icon icon-list"></i>
                                        </a>

                                        <div class="dropdown-menu" aria-labelledby="dropdown05" style="min-width: 14rem !important;left:-41px !important">
                                            <a href="#" onclick="DrAssignDetail(@item.Id)" style="text-decoration: none; padding: 6px">
                                                <i class="icon icon-eye"></i>
                                                Detail
                                            </a>
                                            <br />
                                            <a href="#" onclick="assign(@item.Id)" style="text-decoration: none; padding: 6px">
                                                <i class="icon icon-call"></i>
                                                View Notes
                                            </a>
                                            <br />

                                        </div>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                    }

                }
            </tbody>
        </table>

    </div>
    <div class="row" style="position: absolute; bottom: 20px !important;width: 95%;">
        <div class="col-lg-12">

            <ul class="pagination pagination-rounded mt-5">
                @if (@Model.page != null && @Model.page.TotalPages > 1)
                {

                    if (@Model.page.CurrentPage > 1)
                    {
                        <li class="page-item" title="First">
                            <a class="pageButtonsContactedDr page-link" data-pageno="1"><i class="icon-line-chevrons-left"></i></a>
                        </li>

                        <li class="page-item" title="Previous">
                            <a class="pageButtonsContactedDr page-link" data-pageno="@(@Model.page.CurrentPage - 1)"><i class="icon-line-chevron-left"></i></a>
                        </li>
                    }
                    for (var page = @Model.page.StartPage; page <= @Model.page.EndPage; page++)
                    {
                        string activeClass = @Model.page.CurrentPage == page ? "active" : string.Empty;

                        <li class="page-item @activeClass">
                            <a class="pageButtonsContactedDr page-link" data-pageno="@page">@page</a>

                        </li>
                    }
                    if (@Model.page.CurrentPage < @Model.page.TotalPages)
                    {
                        <li class="page-item" title="Next">
                            <a class="pageButtonsContactedDr page-link" data-pageno="@(@Model.page.CurrentPage + 1)"><i class="icon-line-chevron-right"></i></a>
                        </li>
                        <li class="page-item" title="Last">
                            <a class="pageButtonsContactedDr page-link" data-pageno="@Model.page.TotalPages"><i class="icon-line-chevrons-right"></i></a>
                        </li>
                    }
                }
            </ul>
            <div class="row" style=" margin-top: 20px;">

                <div class="col-md-12" style=" text-align: center;">
                    <a href="/DoctorAssign/ContactedDoctors/@Session["UserId"]" class="btn btn-primary" style="background-color:#1abc9c;">View All</a>
                </div>

            </div>
        </div>
    </div>
</div>
        @Html.Partial("_DoctorsContactedModel")
        <script src="~/Scripts/doctorscontacted.js"></script>
        <script>
    $(".pageButtonsContactedDr").click(function () {
        debugger;
        var data= {
				pageNo: $(this).attr("data-pageNo"),
                search: '@Model.SearchTerm',
                Days: $("#daysContactedDoctors").val()
        }
        SendRequestContactedDoctors(data);
	});

    $('#searchInputContactedDoctors').on('input', function (e) {
        var data = {
            search: $('#searchInputContactedDoctors').val(),
            Days: $("#daysContactedDoctors").val()
        };
        SendRequestContactedDoctors(data);
    });
    function SendRequestContactedDoctors( data) {
        	$.ajax({
			url: '@Url.Action("ContactedDoctorsPage", "SalePersonDashboard")',
			data:data
		})
            .done(function (response) {
                var DDvalue = $('#daysContactedDoctors').val();
                $("#contactedPartial").html(response);
                var search = $("#searchInputContactedDoctors");
                $("#daysContactedDoctors").val(DDvalue);
                var strLength = search.val().length * 2;
                search[0].setSelectionRange(strLength, strLength);

        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	//alert("FAIL");
        });
    };

        </script>
        <script>
            $("#daysContactedDoctors").change(function () {
                var data = {
                    Days: $('#daysContactedDoctors').val()
                };
                SendRequestContactedDoctors(data);

            })
        </script>
<script>
    var ContectedDoctorAssignNotesDB = function (Id) {
        //PV
        debugger
        $("#AddNotesAssignModel").modal("show");
        $('#drID').val(Id);
        ContectedDoctorAssignNotes(Id);

    }

    function ContectedDoctorAssignNotes(Id) {
        //DA Partial View
        debugger
        $.ajax({
            type: "GET",
            url: "/DoctorAssign/GetByDoctorId/" + Id,
            contentType: "application/json;charset=utf-8",
            dataType: "json",
            success: function (data) {
                debugger
                $('#AssignNotesTable2').html('');
                $.each(data, function (i, item) {
                    debugger
                    var assignedName = '';
                    if (item.SalePerson != null) {

                        assignedName = item.SalePerson.User.FullName;
                    }
                    var Discription = '';
                    if (item.Note != null && item.Note.Discription != null) {

                        Discription = item.Note.Discription;
                    }
                    $("#ContactDR").html(item.Doctor.User.FullName);
                    rows = "<tr><td>" + Discription + "</td><td>" + item.Date + "</td><td>" + assignedName + "</td><td><a data-model-id='" + item.Id + "' onclick='DeleteAssignedDoctor(this)' style='cursor:pointer;color:red'><i class='icon icon-trash'></i></a></td></tr>";
                    $('#AssignNotesTable2').append(rows);
                });
            },
            error: function (result) {
                alert('Please Try Again...');
            }
        });
    }
</script>

Vu360Sol.Web/Views/SalePersonDashboard/_VisitorsLearningPartial.cshtml
@model Vu360Sol.ViewModel.SharedViewModels.VisitorViewModelPaginationModel
<div class="row">
    <div class="col-lg-6">
        <div class="input-group">
            <input class="form-control" id="searchInputSPDB" type="text" value="@Model.SearchTerm" placeholder="Search by First Name ,Last Name and Email" style="margin-bottom: 10px;">
        </div>
    </div>
    <div class="col-lg-6">
        <select id="visitorLearningdaysSPDB" name="" class="form-control">
            <option value="1" selected >Today</option>
            <option value="7">Last 7 days</option>
            <option value="30">Last 30 days</option>
        </select>
    </div>
</div>
<div class="table-responsive">
    <table class="table" id="content">
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Practice</th>
                <th>Date</th>
                <th>Time</th>
            </tr>
        </thead>
        <tbody id="myTable">
            @if (Model.visitorViewModels.Count() == 0)
            {
                <tr>
                    <td colspan="3" style="text-align:center;font-size:20px;font-weight:bold;">
                        No Visitor...
                    </td>
                </tr>
            }
            else
            {
                foreach (var item in Model.visitorViewModels)
                {
                    <tr id="contentrow">
                        <td>@item.FullName</td>
                        <td>@item.Email</td>
                        <td>@item.Phone</td>
                        <td>@item.Practice</td>
                        <td>@item.CreatedOn.ToShortDateString()</td>
                        <td>@item.CreatedOn.ToShortTimeString()</td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <ul class="pagination pagination-rounded mt-5">
        @if (@Model.page != null && @Model.page.TotalPages > 1)
        {

            if (@Model.page.CurrentPage > 1)
            {
                <li class="page-item" title="First">
                    <a class="pageButtonsSPDBL page-link" data-pageno="1"><i class="icon-line-chevrons-left"></i></a>
                </li>

                <li class="page-item" title="Previous">
                    <a class="pageButtonsSPDBL page-link" data-pageno="@(@Model.page.CurrentPage - 1)"><i class="icon-line-chevron-left"></i></a>
                </li>
            }
            for (var page = @Model.page.StartPage; page <= @Model.page.EndPage; page++)
            {
                string activeClass = @Model.page.CurrentPage == page ? "active" : string.Empty;

                <li class="page-item @activeClass">
                    <a class="pageButtonsSPDBL page-link" data-pageno="@page">@page</a>

                </li>
            }
            if (@Model.page.CurrentPage < @Model.page.TotalPages)
            {
                <li class="page-item" title="Next">
                    <a class="pageButtonsSPDBL page-link" data-pageno="@(@Model.page.CurrentPage + 1)"><i class="icon-line-chevron-right"></i></a>
                </li>
                <li class="page-item" title="Last">
                    <a class="pageButtonsSPDBL page-link" data-pageno="@Model.page.TotalPages"><i class="icon-line-chevrons-right"></i></a>
                </li>
            }
        }
    </ul>
</div>
<script>
    $(".pageButtonsSPDBL").click(function () {
        var data= {
				pageNo: $(this).attr("data-pageNo"),
                search: '@Model.SearchTerm',
            UserId: $("#hfUserId").val(),
            Days: $("#visitorLearningdaysSPDB").val()

        }
        visitorLearningSendRequest(data);
	});
    $('#searchInputSPDB').on('input', function (e) {
        var data = {
            search: $('#searchInputSPDB').val(),
            Days: $("#visitorLearningdaysSPDB").val()
        };
        visitorLearningSendRequest(data);
    });



    function visitorLearningSendRequest(data) {
        	$.ajax({
			url: '@Url.Action("GetAllVisitorForLearning", "SalePersonDashboard")',
			data:data
		})
            .done(function (response) {
                var DDvalue = $('#visitorLearningdaysSPDB').val();
                $("#partialviewSPDB").html(response);
                $('#visitorLearningdaysSPDB').val(DDvalue);
                var search = $("#searchInputSPDB");
                //search.focus();
                var strLength = search.val().length * 2;
                search[0].setSelectionRange(strLength, strLength);

            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                //alert("FAIL");
            });
    };
</script>
<script>
    $("#visitorLearningdaysSPDB").change(function () {
        var data = {
            Days: $('#visitorLearningdaysSPDB').val()
        };
        visitorLearningSendRequest(data);

    })
</script>