Vu360Sol.Web/Controllers/SearchingController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using Vu360Sol.ViewModel.Search;
using Vu360Sol.ViewModel.SharedViewModels;

namespace Vu360Sol.Web.Controllers
{
    public class SearchingController : Controller
    {
        public ActionResult SearchingIndex()
        {
            return View();
        }
        // GET: Searching
        public ActionResult Search(int PageNo = 1, string Search = "")
        {
            var data = new { PageNo, Search, PageSize = Utility.PageSize };
            var SerializeObject = JsonConvert.SerializeObject(data);
            SearchingPaginationModel pageModel = new SearchingPaginationModel();
            using (var client = Utility.GetHttpClient())
            {
                var myContent = JsonConvert.SerializeObject(SerializeObject);
                var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                var byteContent = new ByteArrayContent(buffer);
                byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/Json");
                var responseTask = client.PostAsync("searching/search/", byteContent);
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<SearchingPaginationModel>();
                    readTask.Wait();
                    pageModel = readTask.Result;
                    pageModel.page = new Pager(pageModel.Count, PageNo, Utility.PageSize);
                    pageModel.SearchTerm = Search;
                    ModelState.Clear();
                    return PartialView("_SearchingPartial", pageModel);

                }
                else
                {
                    pageModel.SearchingViewModels = Enumerable.Empty<SearchingViewModel>();
                    ModelState.AddModelError(string.Empty, "Server error try after some time.");
                }
            }
            return PartialView("_SearchingPartial", pageModel);
        }
    }
}

Vu360Sol.Web/Views/Shared/_DashboardLayout.cshtml
<!doctype html>
<html lang="en">

<head>
    <title>StreamVitals</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <!-- VENDOR CSS -->
    <link rel="stylesheet" href="~/Content/Dashboard/assets/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/Dashboard/assets/vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Content/Dashboard/assets/vendor/linearicons/style.css">
    <link rel="stylesheet" href="~/Content/Dashboard/assets/vendor/chartist/css/chartist-custom.css">
    <!-- MAIN CSS -->
    <link rel="stylesheet" href="~/Content/Dashboard/assets/css/main.css">
    <!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
    <link rel="stylesheet" href="~/Content/Dashboard/assets/css/demo.css">
    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
    <!-- ICONS -->
    <link rel="apple-touch-icon" sizes="76x76" href="~/Content/Dashboard/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" sizes="96x96" href="~/Content/Dashboard/assets/img/favicon.png">
</head>

<body>
    <!-- WRAPPER -->
    <div id="wrapper">
        <!-- NAVBAR -->
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="brand">
                <a href="/Dashboard/Home"><img src="~/Content/canvas/WebSite Images/logo-02.png" alt="Streamvitals" class="img-responsive logo"></a>
            </div>
            <div class="container-fluid">
                <div class="navbar-btn">
                    <button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
                </div>
                <form class="navbar-form navbar-left">
                    <div class="input-group">
                        <input type="text" value="" class="form-control" placeholder="Search dashboard...">
                        <span class="input-group-btn"><button type="button" class="btn btn-primary">Go</button></span>
                    </div>
                </form>
                <div id="navbar-menu">
                    <ul class="nav navbar-nav navbar-right">

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle icon-menu" data-toggle="dropdown">
                                Who We Serve
                            </a>
                            <ul class="dropdown-menu notifications">
                                <li><a href="#" class="notification-item"><span class="dot bg-warning"></span>Practices</a></li>
                                <li><a href="#" class="notification-item"><span class="dot bg-danger"></span>Patients</a></li>
                                <li><a href="#" class="notification-item"><span class="dot bg-success"></span>Partners</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#">
                                How does it work
                            </a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Resource Library
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Resource Library</a></li>
                                <li><a href="#">FAQs</a></li>
                                <li><a href="#">Blog</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                The Company
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Contact Us</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#" class="btn btn-primary" style=" padding: 12px; border-radius: 6px;margin-top: 16px;">Request Demo</a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="~/Content/Dashboard/assets/img/user.png" class="img-circle" alt="Avatar">
                                @*<span>Samuel</span>*@
                                <i class="icon-submenu lnr lnr-chevron-down"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#"><i class="lnr lnr-user"></i> <span>Change Password</span></a></li>
                                <li><a href="#"><i class="lnr lnr-exit"></i> <span>Logout</span></a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- END NAVBAR -->
        <!-- LEFT SIDEBAR -->
        <div id="sidebar-nav" class="sidebar">
            <div class="sidebar-scroll">
                <nav>
                    <ul class="nav">
                        <li><a href="" class="active"><i class="lnr lnr-home"></i> <span>Dashboard</span></a></li>
                        <li><a href="" class=""><i class="lnr lnr-code"></i> <span>Approval</span></a></li>
                        <li><a href="" class=""><i class="lnr lnr-chart-bars"></i> <span>inquiries</span></a></li>
                        <li><a href="" class=""><i class="lnr lnr-cog"></i> <span>SalePersons</span></a></li>
                        <li><a href="" class=""><i class="lnr lnr-alarm"></i> <span>Doctors</span></a></li>

                        <li><a href="" class=""><i class="lnr lnr-dice"></i> <span>Requests For Demo</span></a></li>
                        <li><a href="" class=""><i class="lnr lnr-text-format"></i> <span>Assigned Doctors</span></a></li>
                        <li><a href="" class=""><i class="lnr lnr-linearicons"></i> <span>Contacted Doctors</span></a></li>
                        <li><a href="" class=""><i class="lnr lnr-linearicons"></i> <span>Reports</span></a></li>
                    </ul>
                </nav>
            </div>
        </div>
        <!-- END LEFT SIDEBAR -->
        <!-- MAIN -->
        <div class="main">
            <!-- MAIN CONTENT -->
            <div class="main-content">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>
            <!-- END MAIN CONTENT -->
        </div>
        <!-- END MAIN -->
        <div class="clearfix"></div>
        <footer>
            <div class="container-fluid">
                <p class="copyright">&copy; 2020 <a href="https://www.Streamvitals.com" target="_blank">StreamVitals</a>. Copyrights &copy; 2020 All Rights Reserved by StreamVitals.</p>
            </div>
        </footer>
    </div>
    <!-- END WRAPPER -->
    <!-- Javascript -->
    <script src="~/Content/Dashboard/assets/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/Dashboard/assets/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Content/Dashboard/assets/vendor/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <script src="~/Content/Dashboard/assets/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js"></script>
    <script src="~/Content/Dashboard/assets/vendor/chartist/js/chartist.min.js"></script>
    <script src="~/Content/Dashboard/assets/scripts/klorofil-common.js"></script>
    @RenderSection("scriptDashboard", required: false)
    @*<script>$(function() {
            var data, options;

            // headline charts
            data = {
                labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
                series: [
                    [23, 29, 24, 40, 25, 24, 35],
                    [14, 25, 18, 34, 29, 38, 44],
                ]
            };

            options = {
                height: 300,
                showArea: true,
                showLine: false,
                showPoint: false,
                fullWidth: true,
                axisX: {
                    showGrid: false
                },
                lineSmooth: false,
            };

            new Chartist.Line('#headline-chart', data, options);


            // visits trend charts
            data = {
                labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
                series: [{
                    name: 'series-real',
                    data: [200, 380, 350, 320, 410, 450, 570, 400, 555, 620, 750, 900],
                }, {
                    name: 'series-projection',
                    data: [240, 350, 360, 380, 400, 450, 480, 523, 555, 600, 700, 800],
                }]
            };

            options = {
                fullWidth: true,
                lineSmooth: false,
                height: "270px",
                low: 0,
                high: 'auto',
                series: {
                    'series-projection': {
                        showArea: true,
                        showPoint: false,
                        showLine: false
                    },
                },
                axisX: {
                    showGrid: false,

                },
                axisY: {
                    showGrid: false,
                    onlyInteger: true,
                    offset: 0,
                },
                chartPadding: {
                    left: 20,
                    right: 20
                }
            };

            new Chartist.Line('#visits-trends-chart', data, options);


            // visits chart
            data = {
                labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
                series: [
                    [6384, 6342, 5437, 2764, 3958, 5068, 7654]
                ]
            };

            options = {
                height: 300,
                axisX: {
                    showGrid: false
                },
            };

            new Chartist.Bar('#visits-chart', data, options);


            // real-time pie chart
            var sysLoad = $('#system-load').easyPieChart({
                size: 130,
                barColor: function(percent) {
                    return "rgb(" + Math.round(200 * percent / 100) + ", " + Math.round(200 * (1.1 - percent / 100)) + ", 0)";
                },
                trackColor: 'rgba(245, 245, 245, 0.8)',
                scaleColor: false,
                lineWidth: 5,
                lineCap: "square",
                animate: 800
            });

            var updateInterval = 3000; // in milliseconds

            setInterval(function() {
                var randomVal;
                randomVal = getRandomInt(0, 100);

                sysLoad.data('easyPieChart').update(randomVal);
                sysLoad.find('.percent').text(randomVal);
            }, updateInterval);

            function getRandomInt(min, max) {
                return Math.floor(Math.random() * (max - min + 1)) + min;
            }

        });</script>*@
</body>

</html>

Vu360Sol.Web/Views/Shared/_DetailModelDashboardRequestDemo.cshtml
<div id="requestDemoModel" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-body">
            <div class="modal-content">
                <div class="modal-header" style="background-color:#2f6295 !important">
                    <h4 class="modal-title" id="myModalLabel" style="color: white !important;">Details</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <form id="formnote">
                        <input name="ReferenceId" id="ReferenceId" value="" hidden />
                        @*<div class="row" >
                            <div class="col-3 form-group">
                                <label style="color:#2f6295 !important">FirstName:</label>
                            </div>
                            <div class="col-3 form-group">
                                <label id="fname"></label>
                            </div>
                            <div class="col-3 form-group">
                                <label style="color:#2f6295 !important">LastName:</label>
                            </div>
                            <div class="col-3 form-group">
                                <label id="lname"></label>
                            </div>
                        </div>*@
                        <div class="row" >
                            <div class="col-3 form-group">
                                <label style="color:#2f6295 !important">FullName:</label>
                            </div>
                            <div class="col-9 form-group">
                                <badge style=" background-color: #1abc9c; padding: 8px; border-radius: 6px;">
                                    <label id="fullname" style="color:white !important"> </label>
                                </badge>

                            </div>
                        </div>
                        <div class="row" >
                            <div class="col-3 form-group">
                                <label style="color:#2f6295 !important">Email:</label>
                            </div>
                            <div class="col-9 form-group">
                                <label id="email"></label>
                            </div>
                        </div>

                        <div class="row" >
                            <div class="col-3 form-group">
                                <label style="color:#2f6295 !important">Phone:</label>
                            </div>
                            <div class="col-3 form-group">
                                <label id="phone"></label>
                            </div>
                            <div class="col-3 form-group">
                                <label style="color:#2f6295 !important">Location:</label>
                            </div>
                            <div class="col-3 form-group">
                                <label  id="location"></label>
                            </div>
                        </div>
                       
                        <div class="row" >
                            <div class="col-3 form-group">
                                <label style="color:#2f6295 !important">Date:</label>
                            </div>
                            <div class="col-3 form-group">
                                <label id="date"></label>
                            </div>
                            <div class="col-3 form-group">
                                <label style="color:#2f6295 !important">Time:</label>
                            </div>
                            <div class="col-3 form-group">
                                <label id="time"></label>
                            </div>
                        </div>

                    </form>
                </div>
               
            </div>
        </div>
    </div>
</div>

Vu360Sol.Web/Views/Shared/_DoctorAssignModel.cshtml
<div class="modal fade bs-example-modal-lg" id="assignModel">
    <div class="modal-dialog modal-lg">
        <div class="modal-body">
            <div class="modal-content">
                <div class="modal-header" style="background-color:#2f6295 !important">
                    <h4 class="modal-title" id="myModalLabel" style="color: white !important;">Assign to SalePerson</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <form id="saveNote" style="margin-bottom:0px !important;">
                        
                        <div class="row">
                            <input type="text" hidden name="DoctorId" id="drID" />
                            <div class="col-12 form-group">
                                <label>*Notes:</label>
                                <textarea name="Note.Discription" id="assign-note" class="form-control" cols="30" rows="6" required></textarea>
                                <label id="note-required"></label>
                                <span id="errorSummery" class="text-danger"></span>

                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="salePersonDD">Assign to sale person</label>
                                <select id="salePersonDD" class="form-control" name="SalePersonId" required>
                                </select>
                                <label id="dd-required"></label>

                            </div>
                            <div class="col-4 offset-2  form-group" style="margin-top:23px">
                                <a href="#" id="noteSave" onclick="saveNote()" style="float:left;padding:8px !important;" class="button button-border button-white button-light button-large button-rounded text-right "><span>Save</span></a>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <table class="table">
                        <thead style="background-color:#1abc9c !important; color:white !important;">
                            <tr>
                                <th>Notes</th>
                                <th>Date</th>
                                @*<th>Doctor</th>*@
                                <th>SalePerson</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody id="AssignNotesTable">
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

Vu360Sol.Web/Views/Shared/_DoctorsContactedModel.cshtml
<div class="modal fade bs-example-modal-lg" id="assignModel">
    <div class="modal-dialog modal-lg">
        <div class="modal-body">
            <div class="modal-content">
                <div class="modal-header" style="display:initial !important; background-color:#2f6295 !important">
                    <h4 class="modal-title text-center" id="myModalLabel" style="font-size: 30px;color: white !important;">
                        Notes Details
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </h4>
                    
                </div>
                <div class="modal-body">
                   <div class="row" style="margin-bottom: 20px; margin-top: 20px;">
                       <div class="col-lg-12">
                           <label style="font-size: 20px;">Doctor Name: 
                               <badge id="ContactDR" style="font-size: 20px;text-transform: uppercase;padding-left: 10px;background-color:#1abc9c;color:white;border-radius:5px;padding:5px;"></badge>
                           </label>
                       </div>
                   </div>

                    <table class="table">
                        <thead style="background-color:#1abc9c !important; color:white !important;">
                            <tr>
                                <th>Notes</th>
                                <th>Date</th>
                                <th>Time</th>
                                @*<th>Doctor</th>*@
                                @*<th>SalePerson</th>*@
                                @*<th>Action</th>*@
                            </tr>
                        </thead>
                        <tbody id="AssignNotesTable">
                        </tbody>
                    </table>
                </div>
                <div class="modal-footer">
                    
                </div>
            </div>
        </div>
    </div>
</div>

Vu360Sol.Web/Views/Shared/_Error.cshtml
<!DOCTYPE html>
    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Error</title>
    </head>
    <body>
        <hgroup>
            <h1>Error.</h1>
            <h2>An error occurred while processing your request.</h2>
        </hgroup>
    </body>
    </html>

Vu360Sol.Web/Views/Shared/_GoogleAnalytics.cshtml
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-J4BZFP5R3Y"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', 'G-J4BZFP5R3Y');
</script>

Vu360Sol.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Vu360Solutions</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="background-image: url('/Content/canvas/VUWallpaper (Done).jpg'); background-repeat: no-repeat; background-size: cover;">
    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>*@
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Vu360Solutions</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Vu360Sol.Web/Views/Shared/_SearchingPartial.cshtml
@model Vu360Sol.ViewModel.SharedViewModels.SearchingPaginationModel
@{

}
<style>
    #table {
        height: 95%;
        opacity: 1 !important;
        visibility: visible !important;
        border: none;
        /*margin: auto;*/
        border-radius: 1px;
        overflow: auto;
        /*box-shadow: 0 3px 10px rgba(34, 25, 25, 0.4);*/
        border-collapse: separate;
        background: white;
        padding: 30px;
        width: 100%;
        position: relative !important;
        top: 13%;
        /*left: 2%;*/
        z-index: 100000;
        transition: all 0.25s linear;
        margin-left: auto;
        margin-right: auto;
    }
</style>
<div class="table-responsive" id="table">
    <table class="table centerdiv">
        <tbody>
            @if (Model.SearchingViewModels.Count() == 0)
            {
                <tr>
                    <td colspan="2" class="text-center">
                        No Result.....
                    </td>
                </tr>
            }
            else
            {
                foreach (var item in Model.SearchingViewModels)
                {
                    <tr>
                        <td>
                            <label>
                                <a href="@item.Href" style="color: #1c79bd;">
                                    @item.Title
                                </a>
                            </label>
                            <br />
                            <h5>@item.Description</h5>
                            <p>
                                @item.Paragraph.Substring(0, Math.Min(450, item.Paragraph.Length))<span>..........</span>
                            </p>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <div class="row mb-0 mt-0">
        <div class="col-lg-12 ">
            <ul class="pagination pagination-rounded">
                @if (@Model.page != null && @Model.page.TotalPages > 1)
                {

                    if (@Model.page.CurrentPage > 1)
                    {
                        <li class="page-item" title="First">
                            <a class="pageButtons page-link" data-pageno="1"><i class="icon-line-chevrons-left"></i></a>
                        </li>

                        <li class="page-item" title="Previous">
                            <a class="pageButtons page-link" data-pageno="@(@Model.page.CurrentPage - 1)"><i class="icon-line-chevron-left"></i></a>
                        </li>
                    }
                    for (var page = @Model.page.StartPage; page <= @Model.page.EndPage; page++)
                    {
                        string activeClass = @Model.page.CurrentPage == page ? "active" : string.Empty;

                        <li class="page-item @activeClass">
                            <a class="pageButtons page-link" data-pageno="@page">@page</a>

                        </li>
                    }
                    if (@Model.page.CurrentPage < @Model.page.TotalPages)
                    {
                        <li class="page-item" title="Next">
                            <a class="pageButtons page-link" data-pageno="@(@Model.page.CurrentPage + 1)"><i class="icon-line-chevron-right"></i></a>
                        </li>
                        <li class="page-item" title="Last">
                            <a class="pageButtons page-link" data-pageno="@Model.page.TotalPages"><i class="icon-line-chevrons-right"></i></a>
                        </li>
                    }
                }
            </ul>

        </div>
        @*<div class="col-lg-2">
                <button class="btn btn-default" onclick="HideSearchingPartialView()" style="float: right; border: none;">
                    <i class="icon-times-circle"></i>
                </button>
            </div>*@

    </div>

</div>
<script>
$(".pageButtons").click(function () {
//debugger;
var data= {
pageNo: $(this).attr("data-pageNo"),
search: '@Model.SearchTerm',
}
SendRequest(data);
});
function SendRequest(data) {
$.ajax({
url: '@Url.Action("Search", "Searching")',
data:data
})
.done(function (response) {
//debugger;
$("#searchpartial").html(response);
})
.fail(function (XMLHttpRequest, textStatus, errorThrown) {
//alert("FAIL");
});
};
</script>